### ISSUE TITLE
几个小笔误

### ISSUE THREAD

**Issue by molinjun** [xiaolai/everyones-guide-for-starting-up-on-wechat-network#1]
感谢李老师的分享，颇受启发。的确需要利用好微信生态，打造一个属于自己的品牌和生态。

阅读过程中，不小心发现几个小笔误。望老师复核之后修改。
## 1. 小序中：`做到` 重复了。
![image](https://user-images.githubusercontent.com/21010353/88371465-a98c8a00-cdc6-11ea-9606-154085587f2f.png)

> 按老师的上下文，应该第一个`做到`是 `做过`。

## 2. 伤人 => 商人
章节`2. 你应该把微信当作什么？` 有个小段（如图所示），`伤人` 需要改成 `商人`。
![image](https://user-images.githubusercontent.com/21010353/88371842-667ee680-cdc7-11ea-84ed-75c60bc0d481.png)

**Comment by drizzleing** [comment]
章节4：`商业能力这个东西，死飞非常泛、非常含混的概念`，文中的 `死飞`需要改成`是`

**Comment by kekeyumuku** [comment]
补充一个：
<img width="847" alt="截屏2020-08-01 上午11 44 04" src="https://user-images.githubusercontent.com/25841942/89093459-2f26c000-d3ed-11ea-9d47-faaa09946f94.png">

**Comment by truechuan** [comment]
![image](https://user-images.githubusercontent.com/7081564/89500300-17d44200-d7f4-11ea-9993-2e07421d181e.png)
这个地方应该是教

**Comment by zhouxiugang** [comment]
这也提供一处
![image](https://user-images.githubusercontent.com/55024361/91301632-d4a83600-e7d7-11ea-83b3-be8b734c35d3.png)
