### ISSUE TITLE
这个项目李笑来是不是已经废弃了，做失败了

### ISSUE THREAD

**Issue by yqzhouluyao** [xiaolai/everyones-guide-for-starting-up-on-wechat-network#30]

**Comment by jedlyt** [comment]
您好，合作请加微信：towerinvest

**Comment by yanhaidi** [comment]
谢谢~~ 不过我正在睡大觉，醒来后还要去吃面，吃完面再查看您的邮件，抱歉，休息和吃饭也很重要~~~

**Comment by yqzhouluyao** [comment]
我的意思是，如果李笑来自己都搞不定的话我就不试了，不知道现在什么进展，也没看他再说这个微信平民创业这个事情

**Comment by yqzhouluyao** [comment]
> Reference

合作什么？

**Comment by yanhaidi** [comment]
谢谢~~ 不过我正在睡大觉，醒来后还要去吃面，吃完面再查看您的邮件，抱歉，休息和吃饭也很重要~~~

**Comment by jedlyt** [comment]
您好，合作请加微信：towerinvest

**Comment by yqzhouluyao** [comment]
看完了，很不错很有启发，疑问解决了

**Comment by yqzhouluyao** [comment]
> 您好，合作请加微信：towerinvest

合作什么，定投践行群不是关闭通道了
